{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    {{ range .Values.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  type: {{ .Values.service.type }}
{{ end }}