{{ if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.virtualService.namespace }}
spec:
  hosts:
    - {{ .Values.virtualService.host }}
      {{ if .Values.virtualService.gateways }}
  gateways:
    {{- range .Values.virtualService.gateways }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{ if and .Values.virtualService.httpRoutes (not (empty .Values.virtualService.httpRoutes)) }}
  http:
  {{- range .Values.virtualService.httpRoutes }}
    - name: {{ .name }}
      {{ if and .corsPolicy (not (empty .corsPolicy)) }}
      corsPolicy:
        allowOrigins:
          - exact: "*"
        {{ if and .corsPolicy.allowMethods (not (empty .corsPolicy.allowMethods)) }}
        allowMethods:
          {{ range .corsPolicy.allowMethods }}
          - {{ . | upper }}
          {{ end }}
        {{ end }}
        {{ if and .corsPolicy.allowHeaders (not (empty .corsPolicy.allowHeaders)) }}
        allowHeaders:
          {{ range .corsPolicy.allowHeaders }}
          - {{ . | title }}
          {{ end }}
        {{ end }}
      {{ end }}
      match:
      {{- range .match }}
        - uri:
            prefix: {{ .uri.prefix }}
      {{- end }}
      {{- if .rewrite }}
      rewrite:
        uri: {{ .rewrite.uri }}
      {{- end }}
      route:
      {{- range .route }}
        - destination:
            host: {{ .destination.host }}
            port:
              number: {{ .destination.port.number }}
            {{ if .destination.subset }}
            subset: {{ .destination.subset }}
            {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}

  {{ if and .Values.virtualService.tcpRoutes (not (empty .Values.virtualService.tcpRoutes ) ) }}
  tcp:
  {{- if .Values.virtualService.tcpRoutes }}
  {{- range .Values.virtualService.tcpRoutes }}
    - match:
      {{- range .match }}
        - port: {{ .port }}
      {{- end }}
      route:
      {{- range .route }}
        - destination:
            host: {{ .destination.host }}
            port:
              number: {{ .destination.port.number }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}