{{ if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.configMap.namespace }}
data:
    {{- range $k, $v := .Values.configMap.data }}
  {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}