{{ if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.secrets.namespace }}
data:
    {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}